#ifndef BRUSHDEF_H_INCLUDED
#define BRUSHDEF_H_INCLUDED

enum brush_t{
    BRUSH_RADIAL_GRAD = 0,
    BRUSH_WHITE_NOISE = 1,
    BRUSH_TEXTURE = 2,
    BRUSH_PAINT = 3,
    BRUSH_TERRAIN = 4
};

#endif // BRUSHDEF_H_INCLUDED
